version: "3"
services:
    api:
        build:
            context: .
            dockerfile: src/PublicApi/Dockerfile
        ports:
            - "5000:5000/tcp"
        environment:
            - ASPNETCORE_URLS=http://+:5000